---
- name: install jenkins
  hosts: jenkins_nodes
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: pusula+2023
  tasks:
    - name: Install git
      yum:
        name: git
        state: present
    - name: Install sshpass
      yum:
        name: sshpass
        state: present
    - name: Ensure EPEL repository is present
      yum:
        name: epel-release
        state: present
    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Install java
      yum:
        name: java-11-openjdk-devel
        state: present
    - name: Install maven
      yum:
        name: maven
        state: present
    - name: Install jenkins
      yum:
        name: jenkins
        state: latest
    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes
- name: Start jenkins
  hosts: jenkins_nodes
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: pusula+2023
  tasks:
    - name: Start jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
- name: Install Apache and MySQL
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: pusula+2023
  tasks:
    - name: Install git
      yum:
        name: git
        state: present
    - name: Install sshpass
      yum:
        name: sshpass
        state: present
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Start the httpd service
      service:
        name: httpd
        state: started
        enabled: true
    - name: Install MySQL
      yum:
        name: mysql-server
        state: present
    - name: Start MySQL Service
      service:
        name: mysqld
        state: started
        enabled: true
    - name: Install pip for PyMySQL
      yum:
        name:
          - python3-pip
        state: latest
    - name: Install PyMySQL for MySQL
      pip:
        name: pymysql
    - name: Create MySQL User
      mysql_user:
        name: pusula_shortener
        host: localhost
        password: pusula_shortener_pass
        priv: "*.*:ALL"
    - name: Create MySQL Database
      mysql_db:
        name: pusula_shortener
        login_user: pusula_shortener
        login_password: pusula_shortener_pass
        login_host: localhost
        state: present

- name: Add Remi release repositories
hosts: all
become: yes
become_user: root
become_method: sudo
gather_facts: yes
vars:
  ansible_become_pass: pusula+2023

tasks:
  
  - name: Add Remi release repository
    yum_repository:
      name: remi
      description: Remi's RPM repository for Enterprise Linux 7 - $basearch
      baseurl: http://rpms.remirepo.net/enterprise/7/remi/$basearch/
      gpgcheck: no
      enabled: yes

  - name: Add Remi-safe repository
    yum_repository:
      name: remi-safe
      description: Safe Remi's RPM repository for Enterprise Linux 7 - $basearch
      baseurl: http://rpms.remirepo.net/enterprise/7/safe/$basearch/
      gpgcheck: no
      enabled: yes

  - name: Add Remi PHP 7.4 repository
    yum_repository:
      name: remi-php74
      description: Remi's PHP 7.4 RPM repository for Enterprise Linux 7 - $basearch
      baseurl: http://rpms.remirepo.net/enterprise/7/php74/$basearch/
      gpgcheck: no
      enabled: yes


- name: Install PHP 7.4.33 and required packages
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: pusula+2023

  tasks:
    - name: Install PHP 7.4.33 and required packages
      dnf:
        name:
          - php
          - php-cli
          - php-common
          - php-fpm
          - php-gd
          - php-json
          - php-mbstring
          - php-mysqlnd
          - php-opcache
          - php-pdo
          - php-xml
          - php-tokenizer
          - php-curl
        state: present
      vars:
        dnf_install_repositories:
          - name: remi
            baseurl: http://rpms.remirepo.net/enterprise/7/php74/x86_64/
            gpgcheck: yes
            gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      when: ansible_distribution == "Rocky Linux" and ansible_distribution_major_version == "7"
      
- name: Install PHP Composer
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: pusula+2023
    composer_url: https://getcomposer.org/download/latest-stable/composer.phar
  tasks:
    - name: Composer | Install Composer latest-stable
      get_url:
        url: "{{ composer_url }}"
        checksum: sha256:{{ composer_url }}.sha256sum
        dest: /usr/local/bin/composer.phar
        mode: 755
    - name: Composer | Symlink composer.phar
      file:
        src: composer.phar
        dest: /usr/local/bin/composer
        state: link
