---
- name: Install Git
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: pusula+2023
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present

- name: Install Apache, PHP and MySQL
  hosts: web_nodes
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: pusula+2023
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start the httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Add Remi release repository
      yum_repository:
        name: remi
        description: Remi's RPM repository for Enterprise Linux 7 - $basearch
        baseurl: http://rpms.remirepo.net/enterprise/7/remi/$basearch/
        gpgcheck: no
        enabled: yes

    - name: Install PHP and extensions
      yum:
        name:
          - php
          - php-cli
          - php-common
          - php-fpm
          - php-gd
          - php-json
          - php-mbstring
          - php-mysqlnd
          - php-opcache
          - php-pdo
          - php-xml
          - php-tokenizer
          - php-curl
        state: latest
        enablerepo: remi-php80


    - name: Start and enable PHP
      service:
        name: php-fpm
        state: started
        enabled: true

    - name: Install MySQL
      yum:
        name: mysql-server
        state: present

    - name: Start MySQL Service
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Install pip for PyMySQL
      yum:
        name:
          - python3-pip
        state: latest

    - name: Install PyMySQL for MySQL
      pip:
        name: pymysql

    - name: Create MySQL User
      mysql_user:
        name: pusula_shortener
        host: localhost
        password: pusula_shortener_pass
        priv: "*.*:ALL"

    - name: Create MySQL Database
      mysql_db:
        name: pusula_shortener
        login_user: pusula_shortener
        login_password: pusula_shortener_pass
        login_host: localhost
        state: present


- name: install jenkins
  hosts: jenkins_nodes
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_become_pass: pusula+2023

  tasks:

  - name: Ensure EPEL repository is present
    yum:
      name: epel-release
      state: present

  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Install maven
    yum:
      name: maven
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
