---
- name: Configure jenkins server
  hosts: all
  become: true
  gather_facts: true

  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted

  tasks:
    - name: Install packages
      package:
        name:
          - bash-completion
          - vim
          - nano
        state: latest

    - name: Create pusula user
      user:
        name: pusula
        state: present
        password: "{{ 'pusula+2023' | password_hash('sha512') }}"
        update_password: on_create
        shell: /bin/bash

    - name: Edit SSHD Config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        insertafter: '#PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: restart_sshd

    - name: Add sudo rights for pusula
      copy:
        dest: /etc/sudoers.d/pusula
        content: "pusula ALL=(root) NOPASSWD: ALL"
        backup: true
